sdorra/content-collections

.changeset/fluffy-poets-invite.md
integrations/cli/content-collections.ts
integrations/cli/simple.test.ts
packages/core/src/__tests__/collections/posts.ts
packages/core/src/__tests__/config.001.ts
packages/core/src/config.ts
packages/core/src/json.test.ts
packages/core/src/json.ts
packages/core/src/transformer.test.ts
packages/core/src/transformer.ts
packages/core/src/types.test.ts
samples/mdx/README.md

Validate the resulting objects and ensure that they can be serialized to json

feat(core): ensure result is valid json

---

.changeset/nice-laws-march.md
packages/mdx/src/index.ts

fix(mdx): #23 missing ﻿process.env.NODE_ENV if MDX is used with CLI

---

packages/core/src/writer.ts

Fixes relative path import of config to dts

fix(core): dts relative path import

---

.changeset/nervous-singers-search.md
packages/core/src/cache.test.ts
packages/core/src/cache.ts

Start without cache, if the mapping.json could not be parsed.
Closes: #166

fix(core): #166 do not fail if cache mapping is broken

---

.changeset/fair-chairs-melt.md
packages/core/src/configurationReader.ts
turbo.json

Add an esbuild plugins which mark all paths,
which do not start with "/", "." or ".." as external. This should fix import errors in some situations.

fix(core): mark all packages as external

---

.changeset/few-stingrays-bow.md
packages/core/src/config.ts

Do now show type errors on defineConfig, if declaration is set to true in the tsconfig. 
We export all zod types to fix the type error.
See https://github.com/microsoft/TypeScript/issues/42873

fix(core): #131 type error if declaration is set to true in tsconfig

---

docs/content/mdx.mdx

Seems to be typo in the docs. Once you configure MDX with content-collections, the `mdx` variable is what needs to be used with the `<MDXContent />` component.

fix(website): use mdx instead of content

---

docs/content/mdx.mdx

I think there might be a typo in the documentation for `useMDXComponents`. It seems it should be `useMDXComponent` without the `s`. I had some trouble finding the correct import until I realized this. Just wanted to point it out to help others avoid the same issue! 😅

fix(website): Fix typo in  useMDXComponents

---

.changeset/eleven-games-think.md
packages/core/src/parser.ts

Trim the content before it is passed to the yaml parser. This should fix frontmatter parsing on windows.
Closes: #215

fix(core): #215 frontmatter parsing on windows

---

.changeset/seven-shrimps-train.md
packages/solid-start/src/index.ts

When running `vinxi build` on a Solid Start app the project builds in the following order:
- Router `ssr` at base path `/_build`
- Router `client` at base path `/_build`
- Router `server-fns` at base path `/_server`
Based on this we can see that the `isEnabled` fn will only return `true` on the last phase of the build. In practice this means the build fails on the first step due to missing files in the codegen directory.
This PR ensures the `isEnabled` flag is true for the first step which is the `ssr` one.

Fix Solid Start adapter

---

.changeset/good-pandas-deny.md
docs/transform.mdx
packages/core/src/__tests__/config.005.ts
packages/core/src/config.ts
packages/core/src/transformer.test.ts
packages/core/src/transformer.ts
packages/core/src/types.ts

Extend the context collection with a documents function, which returns all documents of the current collection.
Closes: #268

feat(core): #268 add a function to access sibling documents

---

.changeset/tricky-crabs-build.md
packages/core/package.json
pnpm-lock.yaml

Bundle bundle-require to fix webpack warning on next.js 15
Closes: #309

fix(core): #309 webpack warning on next.js 15

---

.gitattributes
.github/workflows/ci.yml
packages/core/src/collector.test.ts
packages/core/src/collector.ts
packages/core/src/configurationReader.test.ts
packages/core/src/esbuild.ts
packages/core/src/utils.test.ts
packages/core/src/utils.ts
packages/core/src/watcher.test.ts
packages/core/src/writer.test.ts
turbo.json

The globbing library used (tinyglobby) always returns paths with POSIX separators.
This creates problems when a path is generated by the watcher,
which uses the OS-specific separator.
As a result, the file may not be found in the collection if the path separators differ.
This PR also contains changes to fix the unit tests on Windows and run the CI pipeline on Windows as well.
Closes #373

Changes in a sub directory are treated as new documents on windows

---

.changeset/odd-bikes-rule.md
packages/next/src/index.ts

fix(next): #397 double execution if next.config.ts is used on canary

---

samples/next-mdx-static-import/README.md

Hi there, thanks for the awesome library!
I noticed a typo in the `next-mdx-static-import` README, so I created a fix for it. If I missed something obvious, feel free to close this.
By the way, this feature looks great! Will it be released in the next version?

docs: fix the typo in code example of next-mdx-static-import

---

.changeset/nice-ghosts-kick.md
packages/next/src/index.ts

If the parent process has an ID of 1,
we assume that the original parent process was terminated. In this case, we run a new process that evaluates the next configuration, allowing us to skip the initialization.
Closes: #499

fix(next): #499 rerun on sigint

---

.changeset/gorgeous-lamps-call.md
.changeset/popular-geese-remember.md
.changeset/red-books-grin.md
packages/core/src/cache.test.ts
packages/core/src/cache.ts
packages/markdown/src/index.ts
packages/mdx/src/index.ts

The cache API now includes an option to pass an additional key, which helps avoid cache collisions.
Both the mdx and markdown packages have been updated to utilize this new API, resolving the cache collision issue.
Closes: #505

fix: #505 Resolve duplicate cache keys for mdx and markdown packages

---

.changeset/beige-tomatoes-tap.md
packages/next/src/index.ts

We do the check only in dev mode, because in environment like docker it is common that the build is directly started by the init process (pid 1).
https://github.com/sdorra/content-collections/issues/511
Closes: #511

fix(next): #511 check for ppid 1 only on dev

---

.changeset/fresh-goats-accept.md
docs/configuration.mdx
packages/core/src/collector.ts
packages/core/src/config.ts
packages/core/src/index.ts
packages/core/src/parser.ts
packages/core/src/parsers.test.ts
packages/core/src/transformer.test.ts
packages/core/src/transformer.ts
packages/core/src/types.test.ts
pnpm-lock.yaml
samples/xml/README.md
samples/xml/app.ts
samples/xml/content-collections.ts
samples/xml/movies/2001-a-space-odyssey.xml
samples/xml/movies/casablanca.xml
samples/xml/movies/citizen-kane.xml
samples/xml/movies/parasite.xml
samples/xml/movies/pulp-fiction.xml
samples/xml/movies/schindlers-list.xml
samples/xml/movies/seven-samurai.xml
samples/xml/movies/the-godfather.xml
samples/xml/movies/the-shawshank-redemption.xml
samples/xml/movies/the-wizard-of-oz.xml
samples/xml/package.json
samples/xml/simple.test.ts
samples/xml/tsconfig.json
samples/xml/vite.config.ts

Add a new function to the core for creating custom parsers. The function is called defineParser.
The result of this function can be passed to the parser property of a collection.

feat(core): add option to configure custom parser

---

packages/cli/package.json
packages/content-collections/package.json
packages/core/package.json
packages/installer/package.json
packages/integrations/package.json
packages/markdown/package.json
packages/mdx/package.json
packages/next/package.json
packages/remix-vite/package.json
packages/vinxi/package.json
packages/vite/package.json

This should fix the missing changelog in tools like renovate.
Closes: #578

chore: #578 add missing information to package.json

---

docs/quickstart/tanstack-start.mdx

Recently TanStack Start introduced using the `customViteReactPlugin` option in the configuration because soon this will become a norm so that we can choose which vite react plugin (or solidjs plugin) we want to use

Use the `customViteReactPlugin` option in tanstack configuration
